Rails.application.routes.draw do
  root 'articles#home'
  post 'create', to: 'articles#create'
  delete 'delete', to: 'articles#delete'
  post 'upload', to: 'uploads#create'
  post 'usercreate', to: 'authors#register'
  post 'userlogin', to: 'authors#login'
  post 'byid', to: 'articleview#createview'
  get 'articlebylogeduser', to: 'query#allpostedArticles'
  get 'searchbyauthor', to: 'query#articlebyAuthor'
  get 'searchbytopic', to: 'query#articlebyTopic'
  get 'searchbyauthorid', to: 'query#articlebyauthorId'
  get 'finduser', to: 'query#searchuserbyname'
  post 'createComment', to: 'comments#addComment'
  post 'getArticleComment', to: 'comments#getCommentsofArticle'
  post 'likeArticle', to: 'articles#like'
  post 'followto', to: 'followers#followto'
  post 'followedbyuser', to: 'followers#followedbyuser'
  post 'followersofuser', to: 'followers#followersofuser'
  get  'recomendation', to: 'articleview#recomendation'
  post 'userbyid', to: 'query#searchuserbyid'
end